#!/usr/bin/env node
/*
 * Assert the dark theme declares every custom property the default theme does.
 *
 * Run through `make check`, or directly:
 *
 *     node scripts/check-theme.mjs
 *
 * Why this exists
 * ---------------
 * Dark mode is one `html.dark` block generated over a shared theme map, and
 * every component reads the theme through `var(--…)`. There is no per-component
 * dark styling, which means there is also nothing to catch a loss: a custom
 * property present on `html` but missing from `html.dark` does not fail to
 * build, is not invalid CSS, and breaks no lint rule. The components that read
 * it simply keep rendering the light value while the rest of the page is dark.
 *
 * That is the same shape as `padding: none` — a declaration that looks correct
 * and does nothing — and it is the failure the `component-contract` requirement
 * "the dark theme remains a supported surface" exists to prevent.
 *
 * Why it reads the record rather than the stylesheet
 * -------------------------------------------------
 * `.css-declarations.json` is not a second source of truth: task 4.10's
 * `check-declarations` gate fails unless the record matches a fresh build, and
 * this runs after it. Reading the record gives this gate the parsed declaration
 * set without duplicating the stylesheet parser, which took several corrections
 * to get right — multi-line selectors, at-rule scoping, duplicate selectors —
 * and which would be a poor thing to have two of.
 *
 * What this checks that the record comparison cannot
 * --------------------------------------------------
 * `check-declarations` catches a property *removed* from either theme, but only
 * until the record is re-baselined. After that, a property added to `html` and
 * forgotten in `html.dark` is a change nobody notices: the record is updated,
 * every gate passes, and the asymmetry is baked in. A historical check is not a
 * structural one, and this is the structural one.
 */

import { readFileSync } from 'node:fs';

const RECORD = '.css-declarations.json';

const LIGHT_SELECTOR = 'html';
const DARK_SELECTOR = 'html.dark';

let record;
try {
  record = JSON.parse(readFileSync(RECORD, 'utf8'));
} catch (error) {
  process.stderr.write(
    `${RECORD} could not be read: ${error.message}\n` +
      `It is generated by make check-declarations-update. Run that, or\n` +
      `make check-declarations if you expected it to be present.\n`
  );
  process.exit(1);
}

function customProperties(selector) {
  const rules = record.rules.filter((rule) => rule.selector === selector);
  const found = new Set();
  for (const rule of rules) {
    for (const declaration of rule.declarations) {
      if (declaration.property.startsWith('--')) found.add(declaration.property);
    }
  }
  return { rules: rules.length, properties: found };
}

const light = customProperties(LIGHT_SELECTOR);
const dark = customProperties(DARK_SELECTOR);

function fail(lines) {
  process.stderr.write(`${lines.join('\n')}\n`);
  process.exit(1);
}

/*
 * Both blocks must exist before the comparison means anything. If a selector
 * changes -- the theme moved to `:root`, or `.dark` moved off `html` -- then an
 * empty set here would make "dark declares everything light does" vacuously
 * true, which is the worst possible outcome for a gate.
 */
if (light.rules === 0 || light.properties.size === 0) {
  fail([
    `error: no custom properties found on '${LIGHT_SELECTOR}'.`,
    `       Expected the theme block to declare them. If the selector changed,`,
    `       this gate is now comparing nothing -- update LIGHT_SELECTOR rather`,
    `       than letting it pass on an empty set.`,
  ]);
}
if (dark.rules === 0 || dark.properties.size === 0) {
  fail([
    `error: no custom properties found on '${DARK_SELECTOR}'.`,
    `       The dark theme block is missing or renamed. If that is intended, it`,
    `       is a breaking change: the component-contract requirement says a`,
    `       release cannot remove the theme silently, and UPGRADE.md must say so.`,
  ]);
}

const missing = [...light.properties].filter((property) => !dark.properties.has(property));
const extra = [...dark.properties].filter((property) => !light.properties.has(property));

if (missing.length) {
  fail([
    `error: the dark theme is missing ${missing.length} custom propert${missing.length === 1 ? 'y' : 'ies'} the default theme declares.`,
    '',
    ...missing.map((property) => `       ${property}   (declared on ${LIGHT_SELECTOR}, absent from ${DARK_SELECTOR})`),
    '',
    '       Every component reading these will keep rendering its light value',
    '       while the rest of the page is dark. Add them to the dark theme, or',
    '       remove them from the light theme if they are no longer used.',
  ]);
}

process.stdout.write(
  `theme surface is complete: ${dark.properties.size} dark propert${dark.properties.size === 1 ? 'y' : 'ies'} ` +
    `cover all ${light.properties.size} on ${LIGHT_SELECTOR}` +
    (extra.length ? `, plus ${extra.length} dark-only (${extra.join(', ')})` : '') +
    '\n'
);
